#pip freeze > requirements.txt; pip uninstall -r requirements.txt -y; del requirements.txt
from time import perf_counter
import os, json, shutil, tkinter as tk, ctypes, argparse
import threading, multiprocessing as mp
from gui import GUIManager
vipsbin = os.path.join(os.path.dirname(os.path.abspath(__file__)), "vips-dev-8.18", "bin")
os.environ['PATH'] = os.pathsep.join((vipsbin, os.environ['PATH']))
os.add_dll_directory(vipsbin)
if os.path.isdir(vipsbin): os.add_dll_directory(vipsbin)

# get rid of menu bar, VLC style, PURPLE theme, Anim debug colors, font change to dest buttons, UNDO IN DESTW
# should get rid of opencv and use something else. Cuts the filesize to half lol!

# rename this to sessionmanager/
class Imagefile:
    from hashlib import md5
    ANIMATION = "ANIMATION"
    IMAGE = "IMAGE"
    VIDEO = "VIDEO"
    def __init__(self, name, path, ext) -> None:
        "An Imagefile object stores data about the image to help us manage it in the program"
        "Normal attributes"
        self.name = name
        self.truncated_filename = None
        self.path = path
        self.dest = ""
        self.thumbnail = None           # Path to the cached thumbnail in data directory
        self.moved = False              # Used to track if img is sorted
        self.ext = ext.lower()
        self.color = None # dest color
        self.embed = None
        self.color_embed = None
        self.predicted_path = None
        self.dimensions = (-2, 0.0)
        self.pos = None
        "Hash"
        self.id = None              # Hash of img name, mod_time and file_size. This is faster to hash than whole file binary stream.
        self.mod_time = None        # Used by sortimages. Used to hash id.
        self.file_size = None       # Used by canvasimage. Buffers if large enough. Used to hash id.

        "Animation"
        self.frames = []            # PIL frames for animation with tkinter for imagegrid. Generated by ThumbManager (self.animate) for gif, webp and webm.
        self.index = 0              # Used to control what frame is displayed (for imgagegrid).
        self.delay = 100            #Default delay. Used to fill frametimes if speed can't be extracted from file.
        self.thumb = None           # Store the thumbnail imagetk
        self.frame = None           # Reference to gridframe
        self.destframe = None       # Reference to destframe
        self.gridsquare = None
        self.destsquare = None

        "Prediction"
        self.conf = None
        self.pred = None

    def gen_id(self):
        file_name = self.path.replace('\\', '/').split('/')[-1]
        file_stats = os.stat(self.path)
        self.file_size = file_stats.st_size
        self.mod_time = file_stats.st_mtime
        id = f"{file_name} {file_stats.st_size} {file_stats.st_mtime}"
        self.id = Imagefile.md5(id.encode('utf-8')).hexdigest()

    def clear_frames(self):
        self.frames.clear()

    def setdest(self, dest) -> None:
        "Sets imagefile dest and destcolor to desired."
        # if trashed flag, move to "trashed" folder inside our source_dir. during exit, trash these.
        self.moved = False
        self.dest = dest["path"]
        self.color = dest["color"]

    def move(self):
        "Move image from self.path to self.dest and set self.dest = ''. Turn moved flag to True"

        if not self.dest or not os.path.isdir(self.dest): return

        "Pointers"
        name = self.name # in function, better to point  like this or call each time? ###
        old_path = self.path + "" # Perhaps unnecessary, if shutil fails, self.path wont get set to destpath. This is for clarity. This is original path of the file.
        destpath = os.path.join(self.dest, name)

        "Check for conflicts: file with same name already in dest." "Refuse to overwrite anything"
        if os.path.exists(destpath): # path/to/dest/filename
            print(f"File {name[:30]} already exists in destination. No action") # would overwrite with same name otherwise.
            if self.path == destpath:
                return True # already exists there.
            return False

        try:
            shutil.move(self.path, destpath) # Copy -> Delete. If either fail, do exceptions.
            self.path = destpath
            self.dest = ""
            self.moved = True
            return True
        except Exception as e:
            "Shutil failed: Did delete old fail?"
            if os.path.exists(destpath) and os.path.exists(old_path): # This can only remove files created by shutil due to our early exits checking for anything in the way. Safe.
                os.remove(destpath)
                print(f"File {name[:30]} is in use and is unable to delete. Removing created copy from destination.")
            else:
                print(f"Error moving/deleting: {e} {name[:30]}, This error shouldn't be raised at all. Report/investigate")
            return False

class SortImages:
    "Sessionmanager controls walking and interacting with the filesystem, sorting, and saving & loading of prefs and sessions."
    imagelist = [] # Store all Imagefiles
    exclude = []
    assigned = []
    moved = []

    THUMB_FORMAT = ".webp"
    supported_formats = {"png", "gif", "jpg", "jpeg", "bmp", "pcx", "tiff", "webp", "psd", "jfif", "mp4", "mkv", "mov", "m4v", "webm", "avif"}
    threads = 3
    
    script_dir = os.path.dirname(os.path.abspath(__file__))
    data_dir = os.path.join(script_dir, "data")
    trash_dir = os.path.join(script_dir, "Trash")
    os.makedirs(trash_dir, exist_ok=True)
    train_dir = os.path.join(script_dir, "training")
    model_dir = os.path.join(script_dir, "models")
    os.makedirs(model_dir, exist_ok=True)
    prefs_path = os.path.join(script_dir, "_prefs.json")
    themes_path = os.path.join(script_dir, "_themes.json")

    model_classes = None
    names_2_path = None

    # Flags
    last_call_time = 0
    last_sort = (None, False)
    concurrent_frames = 0
    max_concurrent_frames = 10000
    first_run = True

    def __init__(self, gui) -> None:
        "Sortimages setups the program. It creates imagefiles from the folder given, loads and saves prefs, loads and saves sessions, and starts up the gui and other modules."
        self.gui = gui
        technical = gui.jprefs.get("technical", {})
        self.THUMB_FORMAT = technical.get("THUMB_FORMAT", self.THUMB_FORMAT)
        
        gui.fileManager = self
        self.gui.initialize()       # Let GUI initialize fully now with loaded values.

        self.squares_per_page_old = 0
        self.last_assigned_list_for_autosave = []
        self.wait_animation_after_id = None
        
        def load_modules():
            # load expensive modules we need only after gui has appeared
            import av
            import hashlib
            import concurrent.futures
            import numpy
            import PIL
            import pyvips
            
            from destinations import FolderExplorer
            from viewer import Application
            from imagegrid import ImageGrid
            self.gui.imagegrid.thumbs = ImageGrid.ThumbManager(self)
            
            self.update_info()
            self.val_thumb_cache(self.data_dir)

        self.gui.after(10000, self._autosave)
        self.gui.after(1, load_modules)

    def _autosave(self):
        if self.assigned and self.assigned != self.last_assigned_list_for_autosave:
            self.last_assigned_list_for_autosave = self.assigned.copy()
            self.savesession()

        self.gui.after(60000, self._autosave) # autosaves once every minute

    def val_thumb_cache(self, path):
        "Setups cache folder for thumbnails. If folder doesn't exist, it is created. If the first picture in it is not the expected size, the folder is emptied."

        "Data folder doesn't exists: creates it"
        if not (os.path.exists(path) and os.path.isdir(path)):
            os.mkdir(path)
            return

        testable = None
        with os.scandir(path) as entries:
            for entry in entries:
                if entry.is_file() and entry.name.endswith(self.THUMB_FORMAT):
                    testable = entry
                    break

        if not testable:
            print(f"Data folder is empty")
            return

        from PIL import Image
        with Image.open(testable.path) as im:
            width, height = im.size
        if max(width, height) != self.gui.thumbnailsize:
            try:
                print("Removing data folder, thumbnailsize changed")
                shutil.rmtree(path)
                os.mkdir(path)
                print("Re-created data folder.")
            except Exception as e:
                print(f"Couldn't delete/create data folder: {e}")

    def move_temp_to_trash(self):
        trash_dir = self.trash_dir
        if not os.path.isdir(trash_dir): return
        from send2trash import send2trash
        with os.scandir(trash_dir) as files:
            for file in files:
                try: send2trash(file.path)
                except Exception as e: print("Trashing error", e)

    def purge_cache(self):
        data_dir = self.data_dir
        if os.path.isdir(data_dir):
            with os.scandir(data_dir) as files:
                ids = {entry.file.id for entry in self.gui.imagegrid.image_items}
                for file in files:
                    id = file.name.rsplit(".", 1)[0]
                    if id in ids: continue
                    try: os.remove(file.path)
                    except Exception as e: print("Failed to remove old cached thumbnails from the data directory.", e)

    def saveprefs(self, gui):
        "Saves all customizable stuff to prefs.json."
        if gui.middlepane_frame.winfo_width() == 1: # Do not try to save invalid value
            pass
        else:
            gui.middlepane_width = gui.middlepane_frame.winfo_width()

        source = gui.source_entry_field.get() if os.path.exists(gui.source_entry_field.get()) else ""
        destination = gui.destination_entry_field.get() if os.path.exists(gui.destination_entry_field.get()) else ""

        save = {
            "paths": {
                "source": source.strip(),
                "destination": destination.strip(),
                "lastsession": gui.lastsession,
                "exclude": self.exclude,
                "categories": self.gui.categories,
                "excludes": self.gui.excludes,
                "model": self.gui.model_path
            },
            "technical": {
                "threads": self.threads, # hard coded to be no more than 3 to avoid lag.
                "max_concurrent_frames": self.max_concurrent_frames,
                "THUMB_FORMAT": self.THUMB_FORMAT,
                "thumbnailsize": gui.thumbnailsize,
                "squares_per_page": gui.squares_per_page_intvar.get(),
                "hotkeys": gui.hotkeys,
                "do_debug": gui.do_debug.get()
            },
            "user": {
                "theme": gui.theme.get(),
                "display_order": gui.display_order.get(),
                "show_next": gui.show_next.get(),
                "dock_view": gui.dock_view.get(),
                "dock_side": gui.dock_side.get(),
                "main_geometry": "zoomed" if self.gui.state() == "zoomed" else gui.winfo_geometry(),
                "viewer_geometry": gui.viewer_geometry,
                "destpane_geometry":gui.destpane_geometry,
                "leftpane_width": max(gui.leftui.winfo_width(), 50),
                "middlepane_width": gui.middlepane_width if int(gui.winfo_geometry().split("x", 1)[0])-gui.middlepane_width-gui.leftui.winfo_width() > gui.thumbnailsize//2 else gui.middlepane_width-gui.thumbnailsize//2,
                "images_sorted":gui.images_sorted,
            }
        }
        save["viewer"] = gui.viewer_prefs

        "Save to prefs.json"
        try:
            with open(self.prefs_path, "w+") as json_file:
                json.dump(save, json_file, indent=4)
        except Exception as e:
            print(("Failed to save prefs:", e))

        "Save session"
        self.savesession()


    def savesession(self):
        start = perf_counter()
        if not self.assigned: return
        savelocation = gui.lastsession or os.path.join(self.script_dir, "_last_session.json")

        if not savelocation: return

        colors = {}
        assigned = []
        for x in self.assigned:
            colors[x.dest] = x.color
            assigned.append((x.path, x.dest))

        save = {"destination": self.gui.destination_folder, "source": self.gui.source_folder, "colors": colors, "assigned": assigned, "moved": self.moved}

        try:
            with open(savelocation, "w+") as json_file:
                json.dump(save, json_file, indent=4)
                gui.lastsession = savelocation
        except Exception as e:
            print(("Failed to save session:", e))
        
        print("session saved in:", perf_counter()-start)

    def loadsession(self):
        gui = self.gui

        if gui.session_entry_field:
            lastsession = gui.session_entry_field.get()
            if not lastsession: return
            sessionpath = os.path.normpath(os.path.join(self.script_dir, lastsession))
            gui.lastsession = lastsession if os.path.isfile(sessionpath) else gui.lastsession
        
        if not os.path.exists(sessionpath):
            print("That session doesn't exist!")
            return

        with open(sessionpath, "r") as json_file:
            sdata = json_file.read()
            savedata = json.loads(sdata)

        temp = []
        for x in savedata["assigned"]:
            path, dest = x
            name = os.path.basename(path)
            parts = name.rsplit(".", 1)
            if len(parts) == 2:
                n, ext = parts
                ext = ext.lower()
            else:
                n = parts[0]
                ext = ""
            obj = Imagefile(name, path, ext.lower())
            obj.dest = dest
            obj.color = savedata["colors"][dest]
            temp.append(obj)

        self.assigned = temp

        self.validate()

    def moveall(self): # the bindhandler could do this as it is activated by a button.
        gui = self.gui
        temp = self.assigned.copy()

        successfull = []
        for obj in temp:
            success = obj.move()
            if success: # If move was successfull
                self.assigned.remove(obj)
                self.moved.append(obj)
                #imagegrid.moved.append(x)

                gui.images_sorted += 1
                assigned_count, images_left = len(self.assigned), len(self.all_objs)-len(self.assigned)-len(self.moved)
                title = f"Assigned: {assigned_count}, Left: {images_left}" + "" if self.gui.displayed_obj is None else f" - {self.gui.displayed_obj.name}"
                gui.winfo_toplevel().title(title)

                successfull.append(obj)

    def setDestination(self, dest, caller=None): # could move to imagegrid, where the assigned list originates from.
        f = self.gui.focus_get()
        if hasattr(f, "widgetName") and f.widgetName == "entry" or (caller is not None and hasattr(caller, "widget") and isinstance(caller.widget, tk.Entry)): return

        current_time = perf_counter()
        if current_time - self.last_call_time < 0.1: return
        self.last_call_time = current_time

        focused_window, imagegrid, destw = self.gui.bindhandler.window_focused, self.gui.imagegrid, self.gui.folder_explorer.destw
        grid = imagegrid if focused_window == "GRID" else destw if focused_window == "DEST" else None
        if grid is None: print("Error grid is none")
        marked = grid.selected
        if not marked: marked = [grid.image_items[grid.current_selection]] if grid.image_items and grid.current_selection is not None else None
        if not marked: return
        grid.move([x.file for x in marked], dest, origin=True)
        for x in marked:
            imagefile = x.file
            imagefile.setdest(dest)

        grid.selected.clear()
        if (self.gui.current_view.get() == "Unassigned"): self.load_more()
        assigned_count, images_left = len(self.assigned), len(self.all_objs)-len(self.assigned)-len(self.moved)
        title = f"Assigned: {assigned_count}, Left: {images_left}" + "" if self.gui.displayed_obj is None else f" - {self.gui.displayed_obj.name}"
        gui.winfo_toplevel().title(title)

    def validate(self, btn=None): # new session
        if btn and self.first_run: return # The first run requires you to press "New Session"
        gui = self.gui
        
        if gui.session_entry_field:
            lastsession = gui.session_entry_field.get()
            if not lastsession or lastsession == "No last Session": lastsession = "_last_session.json"
            if "/" not in lastsession and "\\" not in lastsession: # just name
                sessionpath = os.path.normpath(os.path.join(self.script_dir, lastsession))
            else:
                sessionpath = lastsession
            gui.lastsession = sessionpath or gui.lastsession
        
        bad = False
        for ref, entry in (("src", gui.source_entry_field), ("dest", gui.destination_entry_field)):
            clean = os.path.normpath(entry.get().strip().strip('"'))
            if not os.path.isdir(clean):
                entry.delete(0, tk.END); entry.insert(0, "ERROR"); entry.xview_moveto(1.0)
                bad = True
                continue
            entry.delete(0, tk.END); entry.insert(0, clean+"  "); entry.xview_moveto(1.0)
            if ref == "src": gui.source_folder = clean
            elif ref == "dest": gui.destination_folder = clean
        if bad: return

        if self.first_run: gui.guisetup()
        else:
            if gui.Image_frame: gui.Image_frame.set_image(None)
            if gui.second_window_viewer: gui.second_window_viewer.set_image(None)
        
        gui.folder_explorer.set_view(gui.destination_folder)

        print(f'\nSource:   "{gui.source_folder}"\nTarget:   "{gui.destination_folder}"\n')
        samepath = (gui.source_folder == gui.destination_folder)
        os.makedirs(self.data_dir, exist_ok=True)
        self.imagelist = self.walk(gui.source_folder, samepath)
        self.first_run = False

        assigned_count, images_left = len(self.assigned), len(self.imagelist)
        title = f"Assigned: {assigned_count}, Left: {images_left}" + "" if gui.displayed_obj is None else f" - {gui.displayed_obj.name}"
        gui.winfo_toplevel().title(title)

        gui.imagegrid.clear_canvas(unload=True)
        self.sort_imagelist()

    def load_more(self): # should be deprecated with virtual grid
        count_in_grid = len(self.gui.imagegrid.image_items)
        amount = self.gui.squares_per_page_intvar.get()
        to_load = amount - count_in_grid
        left = len(self.imagelist)
        items = min(to_load, left)
        if items <= 0: return
        load = self.imagelist[-items:]
        load.reverse()
        self.imagelist = self.imagelist[:-items]
        self.gui.imagegrid.add(load)

        if self.gui.prediction.get():
            self.gui.squares_per_page_intvar.set(self.squares_per_page_old)

    def walk(self, src, samepath): # IMAGEGRID should do this.
        imagelist = []
        for root, dirs, files in os.walk(src, topdown=True):
            dirs[:] = [d for d in dirs if d not in self.exclude]
            for name in files:
                parts = name.rsplit(".", 1)
                if len(parts) == 2:
                    n, ext = parts
                    ext = ext.lower()
                else:
                    n = parts[0]
                    ext = ""
                if ext in self.supported_formats:imagelist.append(Imagefile(name, os.path.join(root, name), ext))
            if samepath: break
        if self.assigned:
            identity_check = set([x.path for x in self.assigned])
            return [x for x in imagelist if x.path not in identity_check]
        self.last_sort = (self.last_sort[0], not self.last_sort[1])
        return imagelist

    def wait_indicator_animation_start(self, msg, suffix="...", start_index=0):
        self.gui.train_status_var.set(f"{msg} {' '*(len(suffix)-(start_index+1))}{suffix[:start_index]}") # stylistic
        #self.gui.train_status_var.set(f"{msg}{suffix[:start_index]}{' '*(len(suffix)-(start_index+1))}") # add 1 extra char to suffix
        self.wait_animation_after_id = self.gui.after(100, self.wait_indicator_animation_start, msg, suffix, (start_index + 1) % (len(suffix)))

    def sort_imagelist(self): # imagegrid should do this
        # remove from imagelist, but add back from image_items
        from operator import attrgetter
        from natsort import natsorted
        if self.first_run: return
        gui = self.gui

        def after_tasks():
            self.all_objs = self.imagelist.copy() # unassigned store
            amount = self.gui.squares_per_page_intvar.get()
            left = len(self.imagelist)
            items = min(amount, left)

            load = self.imagelist[-items:]
            load.reverse()

            gui.imagegrid.clear_canvas(unload=True, new_list=load)# does this limit assgined moved ist wtf?
            self.load_more()
            if self.wait_animation_after_id: self.gui.after_cancel(self.wait_animation_after_id)
            self.gui.train_status_var.set("")

        if self.gui.current_view.get() != "Unassigned": return


        grid_objects = [entry.file for entry in gui.imagegrid.image_items] # unassigned loaded list, rest is self.imagelist
        self.imagelist.extend(reversed(grid_objects))

        MODE = gui.display_order.get().lower()
        if self.last_sort[0] == MODE.lower(): self.last_sort = (self.last_sort[0], not self.last_sort[1])
        else: self.last_sort = (MODE.lower(), False)

        self.wait_indicator_animation_start("Sorting")
        if gui.prediction.get():
            def run():
                # reorder by confidence.
                CONF_THRESHOLD = 0.4
                no_pred = []
                predictable = []
                for x in self.imagelist:
                    if x.pred:
                        predictable.append(x)
                    else:
                        no_pred.append(x)

                # group together with same predicted label.
                classes = {}
                for x in predictable:
                    if classes.get(x.pred, None) == None:
                        classes[x.pred] = []
                    classes[x.pred].append(x)

                # distinguish using colors
                for key, c in classes.items():
                    c[:] = [x for x in c if x.conf >= CONF_THRESHOLD]
                    if len(c) < 2:
                        continue

                    match MODE.lower():
                        case "filename":
                            classes[key] = natsorted(c, key=attrgetter("name"), reverse=True if self.last_sort[1] == False else False)
                        case "type":
                            classes[key] = natsorted(c, key=attrgetter("name"), reverse=True if self.last_sort[1] == False else False)
                            c1 = classes[key]
                            c1.sort(key=lambda x: (x.ext.lower() not in ("gif", "webm", "mp4", "webp"), x.ext.lower()), reverse=True if self.last_sort[1] == False else False)
                        case "date":
                            for obj in c:
                                obj.mod_time = os.path.getmtime(obj.path)
                            c.sort(key=attrgetter("mod_time"), reverse=False if self.last_sort[1] == False else True)
                        case "size":
                            for obj in c:
                                file_stats = os.stat(obj.path)
                                obj.file_size = file_stats.st_size
                            c.sort(key=attrgetter("file_size"), reverse=False if self.last_sort[1] == False else True)
                        case "smart":
                            # Groups by filename, Normal, numeric and hashed.
                            # Each group is sorted by natsort, or in case of hashed, modification date.
                            import re
                            def get_file_metadata(name):
                                stem = os.path.splitext(name)[0]
                                # Split by any of these: _ - . ( ) [ ] or whitespace
                                segments = [s.strip() for s in re.split(r'[_.\-\(\)\[\]\s]', stem) if s.strip()]

                                # Atoms: Strictly letters (no numbers allowed)
                                atoms = [s.lower() for s in segments if s.isalpha() and len(s) > 1]

                                # Identify the "Kind"
                                clean_total = "".join(segments)
                                if clean_total.isdigit():
                                    kind = "numeric"
                                elif not atoms:
                                    kind = "hashed" # Has segments, but none are pure words
                                else:
                                    kind = "alpha"

                                return set(atoms), len(segments), kind

                            alpha = []
                            numeric = []
                            hashed = []
                            for x in c:
                                atoms, length, kind = get_file_metadata(x.name)
                                if kind == "alpha": alpha.append(x)
                                elif kind == "hashed": hashed.append(x)
                                else: numeric.append(x)

                            alpha = natsorted(alpha, key=attrgetter("name"), reverse=False if self.last_sort[1] == False else True)
                            numeric = natsorted(numeric, key=attrgetter("name"), reverse=False if self.last_sort[1] == False else True)

                            for obj in hashed:
                                obj.mod_time = os.path.getmtime(obj.path)
                            hashed.sort(key=attrgetter("mod_time"), reverse=False if self.last_sort[1] == False else True)

                            combined = alpha+hashed+numeric
                            combined.reverse()
                            c[:] = combined
                        case "dimensions":
                            from PIL import Image
                            from imageio import get_reader # 130 ms
                            for obj in c:
                                if obj.dimensions == (-2, 0.0):
                                    if obj.ext in ("mp4", "webm"):
                                        try:
                                            reader = None
                                            reader = get_reader(obj.path)
                                            pil_img = Image.fromarray(reader.get_data(0))
                                            w, h = pil_img.size
                                            ratio = w/h # ratio
                                            if w == h: orientation = 0.0
                                            elif w < h: orientation = -1.0
                                            else: orientation = 1.0
                                            obj.dimensions = (orientation, ratio)
                                        except Exception as e:
                                            print(f"Couldn't read: {obj.name} : Error: {e}")
                                        finally:
                                            if reader: reader.close()
                                    else:
                                        try:
                                            with Image.open(obj.path) as pil_img:
                                                w, h = pil_img.size
                                                ratio = w/h # ratio
                                                if w == h: orientation = 0.0
                                                elif w < h: orientation = -1.0
                                                else: orientation = 1.0
                                                obj.dimensions = (orientation, ratio)
                                        except Exception as e:
                                            print("sorting error when fetching dimensiosns", obj.path, e)

                            c.sort(key=attrgetter("dimensions"), reverse=False if self.last_sort[1] == False else True)

                        case "histogram": # threaded gen
                            self.gui.train_status_var.set("Sorting...")
                            self.reorder_as_nearest1(c, reverse=self.last_sort[1])
                        case "nearest":
                            self.reorder_as_nearest(c, reverse=self.last_sort[1])
                        case "confidence":
                            c.sort(key=lambda x: x.conf, reverse=False if self.last_sort[1] == False else True)
                classes = sorted(list(classes.values()), key=lambda x: len(x), reverse=False if self.last_sort[1] == False else True) # sorted by class and conf

                predictable = []
                for x in classes:
                    predictable.extend(x)
                self.squares_per_page_old = self.gui.squares_per_page_intvar.get()
                self.gui.squares_per_page_intvar.set(len(predictable))
                def helper():
                    self.imagelist = predictable + no_pred
                    after_tasks()
                gui.after(1, helper)
            def helper():
                self.reorder_as_nearest(self.imagelist, reverse=self.last_sort[1])
                gui.after(1, run)
            if MODE == "nearest":
                a = threading.Thread(target=helper, daemon=True)
            else:
                a = threading.Thread(target=run, daemon=True)
            a.start()
            return
        else:
            match MODE.lower():
                case "filename":
                    self.imagelist = natsorted(self.imagelist, key=attrgetter("name"), reverse=True if self.last_sort[1] == False else False)
                case "type":
                    self.imagelist = natsorted(self.imagelist, key=attrgetter("name"), reverse=True if self.last_sort[1] == False else False)
                    self.imagelist.sort(key=lambda x: (x.ext.lower() not in ("gif", "webm", "mp4", "webp"), x.ext.lower()), reverse=True if self.last_sort[1] == False else False)
                case "date":
                    for obj in self.imagelist:
                        obj.mod_time = os.path.getmtime(obj.path)
                    self.imagelist.sort(key=attrgetter("mod_time"), reverse=False if self.last_sort[1] == False else True)
                case "size":
                    for obj in self.imagelist:
                        file_stats = os.stat(obj.path)
                        obj.file_size = file_stats.st_size
                    self.imagelist.sort(key=attrgetter("file_size"), reverse=False if self.last_sort[1] == False else True)
                case "smart":
                    # sort out HASHED files that fuck up everything
                    # sORT Out purely number based.
                    import re
                    def get_file_metadata(name):
                        stem = os.path.splitext(name)[0]
                        # Split by any of these: _ - . ( ) [ ] or whitespace
                        segments = [s.strip() for s in re.split(r'[_.\-\(\)\[\]\s]', stem) if s.strip()]

                        # Atoms: Strictly letters (no numbers allowed)
                        atoms = [s.lower() for s in segments if s.isalpha() and len(s) > 1]

                        # Identify the "Kind"
                        clean_total = "".join(segments)
                        if clean_total.isdigit():
                            kind = "numeric"
                        elif not atoms:
                            kind = "hashed" # Has segments, but none are pure words
                        else:
                            kind = "alpha"

                        return set(atoms), len(segments), kind

                    alpha = []
                    numeric = []
                    hashed = []
                    for x in self.imagelist:
                        atoms, length, kind = get_file_metadata(x.name)
                        if kind == "alpha": alpha.append(x)
                        elif kind == "hashed": hashed.append(x)
                        else: numeric.append(x)

                    alpha = natsorted(alpha, key=attrgetter("name"), reverse=False if self.last_sort[1] == False else True)
                    numeric = natsorted(numeric, key=attrgetter("name"), reverse=False if self.last_sort[1] == False else True)

                    for obj in hashed:
                        obj.mod_time = os.path.getmtime(obj.path)
                    hashed.sort(key=attrgetter("mod_time"), reverse=False if self.last_sort[1] == False else True)


                    combined = alpha+hashed+numeric
                    combined.reverse()
                    # Replace the original list
                    self.imagelist[:] = combined
                case "dimensions":
                    from PIL import Image
                    for obj in self.imagelist:
                        if obj.dimensions == (-2, 0.0):
                            if obj.ext in ("mp4", "webm", "mkv", "m4v", "mov"):
                                import av
                                try:
                                    container = None
                                    container = av.open(obj.path)
                                    
                                    video = container.streams.video[0]
                                    
                                    w = video.width
                                    h = video.height
                                    
                                    ratio = w / h
                                    if w == h: 
                                        orientation = 0.0
                                    elif w < h: 
                                        orientation = -1.0
                                    else: 
                                        orientation = 1.0
                                        
                                    obj.dimensions = (orientation, ratio)
                                
                                except Exception as e:
                                    print(f"Couldn't read: {obj.name} : Error: {e}")
                                finally:
                                    if container:
                                        container.close()
                            else:
                                try:
                                    with Image.open(obj.path) as pil_img:
                                        w, h = pil_img.size
                                        ratio = w/h # ratio
                                        if w == h: orientation = 0.0
                                        elif w < h: orientation = -1.0
                                        else: orientation = 1.0
                                        obj.dimensions = (orientation, ratio)
                                except Exception as e:
                                    print("sorting error when fetching dimensiosns", obj.path, e)

                    self.imagelist.sort(key=attrgetter("dimensions"), reverse=True if self.last_sort[1] == False else False)
                case "histogram": # threaded gen
                    def helper1():
                        self.reorder_as_nearest1(self.imagelist, reverse=self.last_sort[1])
                        gui.after(1, after_tasks)
                    a = threading.Thread(target=helper1, daemon=True) # dont freeze the program do it threaded
                    a.start()
                    print("Started thread to sort by Histogram. Please wait.")
                    return
                case "nearest": # threaded gen
                    def helper1():
                        self.reorder_as_nearest(self.imagelist, reverse=self.last_sort[1])
                        gui.after(1, after_tasks)
                    a = threading.Thread(target=helper1, daemon=True) # dont freeze the program do it threaded
                    a.start()
                    print("Started thread to sort by Nearest Neighbour. Please wait.")
                    return

        after_tasks()

    def reorder_as_nearest1(self, imagefiles, reverse=False): # imagegrid should do this
        from concurrent.futures import ThreadPoolExecutor
        import os
        from time import perf_counter

        start = perf_counter()

        # 1. ALIGN STARTING ORDER (The "Seed")
        # Matches: sorted(image_paths, key=lambda x: os.path.basename(x).rsplit(".",1)[0])
        # We sort by the file name without extension to ensure the same starting point.
        test = sorted(imagefiles, key=lambda x: os.path.basename(x.path).rsplit(".", 1)[0])

        import numpy as np
        from PIL import Image
        from imagegrid import ImageGrid
        def gen_thumb(obj, size, cache_dir): # session just calls this for displayedlist  
            interp = ImageGrid.ThumbManager.av.video.reformatter.Interpolation.AREA
            THUMB_FORMAT = self.THUMB_FORMAT

            if not obj.id: obj.gen_id()

            pil_img = None
            failed = False

            if cache_dir:
                thumbnail_path = os.path.join(cache_dir, f"{obj.id}{THUMB_FORMAT}")
                
            if cache_dir and os.path.exists(thumbnail_path): # default and train will have cache_dir
                try:
                    thumb = None
                    with ImageGrid.ThumbManager.Image.open(thumbnail_path) as pil_img: # pil is faster here.
                        pil_img.load()
                        obj.thumbnail = thumbnail_path
                    return pil_img
                except Exception as e:
                    print(f"Pillows couldn't load thumbnail from cache: {obj.name} : Error: {e}.")
                    failed = True

            vips_used = False
            av_formats = {"webm", "mp4", "mkv", "m4v", "mov", "gif"}
            if obj.ext in av_formats: #Webm, mp4
                pix_fmt = 'rgba' if any(f in obj.ext for f in ["webp", "gif"]) else 'rgb24'
                container = None
                try:
                    container = ImageGrid.ThumbManager.av.open(obj.path)
                    stream = container.streams.video[0]
                    w, h = stream.width, stream.height
                    max_size = 256
                    scale = max_size / max(w, h)
                    new_w = int(w * scale)
                    new_h = int(h * scale)

                    for frame in container.decode(stream):
                        resized_frame = frame.reformat(width=new_w, height=new_h, interpolation=interp, format=pix_fmt)
                        pil_img = resized_frame.to_image()
                        pil_img.save(thumbnail_path, format=THUMB_FORMAT[1:], quality=100)
                        obj.thumbnail = thumbnail_path
                        return pil_img
                        break
                except Exception as e:
                    print(f"PyAV thumbnail error for {obj.name}: {e}")
                    failed = True
                finally:
                    if container:
                        container.close()
            else:
                try:
                    vips_img = ImageGrid.ThumbManager.pyvips.Image.thumbnail(obj.path, size)
                    buffer = vips_img.write_to_memory()
                    pil_format = self.get_mode(vips_img)
                    pil_img =  ImageGrid.ThumbManager.Image.frombytes(pil_format, (vips_img.width, vips_img.height), buffer, "raw")
                    vips_used = True
                except Exception as e: # Pillow fallback
                    print(f"Pyvips couldn't create thumbnail: {obj.name} : Error: {e}.")
                    failed = True
                if not vips_used or failed:
                    try:
                        with ImageGrid.ThumbManager.Image.open(obj.path) as pil_img:
                            pil_img.thumbnail((size, size))
                    except Exception as e:
                        print(f"Pillows couldn't create thumbnail, either: {obj.name} : Error: {e}")
                        failed = True

            if not pil_img: return

            if pil_img.mode != "RGBA": pil_img = pil_img.convert("RGBA")

            # save it to cache if we can
            if cache_dir: # default and train
                pil_img.save(thumbnail_path, format=THUMB_FORMAT[1:], quality=100)
                thumb = None
            obj.thumbnail = thumbnail_path
            return pil_img
            
        def extract_features_pillow(obj): # this could actually load and generate the thumbnail proper.
            try:
                # Load and convert to HSV using Pillow
                img = gen_thumb(obj, self.gui.thumbnailsize, self.data_dir).convert('HSV')
                img_arr = np.array(img)
                
                # Calculate 3D Histogram: 8 bins per channel
                # img_arr shape is (H, W, 3)
                h, s, v = img_arr[:,:,0], img_arr[:,:,1], img_arr[:,:,2]
                
                # Define bins (8 bins each)
                h_bins = np.linspace(0, 180, 9)
                s_bins = np.linspace(0, 256, 9)
                v_bins = np.linspace(0, 256, 9)
                hist, _ = np.histogramdd((h.ravel(), s.ravel(), v.ravel()), bins=(h_bins, s_bins, v_bins))

                # old new above
                #bins = [np.linspace(0, 255, 9) for _ in range(3)]
                #hist, _ = np.histogramdd((h.ravel(), s.ravel(), v.ravel()), bins=bins)
                
                # Normalize
                hist = hist.astype(np.float32)
                sum_hist = np.sum(hist)
                if sum_hist > 0:
                    hist /= sum_hist
                    
                return hist.flatten(), obj
            except Exception as e:
                return None, None

        # 2. FEATURE EXTRACTION
        features_list = []
        objs_to_encode = []

        # Using ThreadPool to maintain speed while using cv2.imread
        with ThreadPoolExecutor(max_workers=max(1, self.threads - 1)) as executor:
            results = list(executor.map(extract_features_pillow, test))

        for feat, obj in results:
            if feat is not None:
                features_list.append(feat)
                objs_to_encode.append(obj)

        if not objs_to_encode:
            return

        # 3. GREEDY CHAIN (EXACT REPLICATION)
        # unvisited = set(valid_paths)
        unvisited_indices = list(range(len(features_list)))

        # current = valid_paths[0]
        current_idx = unvisited_indices.pop(0)
        order = [current_idx]

        def bhattacharyya_dist(h1, h2):
            # 1. Calculate the Bhattacharyya Coefficient (overlap)
            # Both h1 and h2 must be normalized so sum(h) == 1
            bc = np.sum(np.sqrt(h1 * h2))
            
            # 2. Return the Hellinger distance (what OpenCV calls BHATTACHARYYA)
            # We use max(0, ...) to prevent tiny floating point errors from becoming negative
            return np.sqrt(max(0, 1 - bc))

        while unvisited_indices:
            best_match_local_idx = -1
            min_dist = float('inf')
            current_feat = features_list[current_idx]

            for i, cand_idx in enumerate(unvisited_indices):
                dist = bhattacharyya_dist(current_feat, features_list[cand_idx])

                if dist < min_dist:
                    min_dist = dist
                    best_match_local_idx = i
                    
            # current = best_match
            current_idx = unvisited_indices.pop(best_match_local_idx)
            order.append(current_idx)

        # 4. FINAL LIST UPDATE
        ordered_objs = [objs_to_encode[idx] for idx in order]

        # Collect any files that failed to load (to prevent losing data)
        loaded_paths = {o.path for o in objs_to_encode}
        remaining = [o for o in imagefiles if o.path not in loaded_paths]

        # Update the original list reference in-place
        imagefiles[:] = ordered_objs + remaining

        if not reverse:
            imagefiles.reverse()

        print(f"✅ Exact Color Sort complete: {len(ordered_objs)} images in {perf_counter()-start:.4f}s")

    def reorder_as_nearest(self, imagefiles, optimization=False, reverse=False): # imagegrid should do this
        from PIL import Image
        import numpy as np
        from concurrent.futures import ThreadPoolExecutor, as_completed
        TARGET_SIZE = (224, 224)
        BATCH_SIZE = 64
        #SAVE_PATH = r"C:\Users\4f736\Downloads\sort\results"
        PRESET = 1 # 2
        #os.makedirs(SAVE_PATH, exist_ok=True)
        start = perf_counter()
        TARGET_SIZE = 224  # used by pyvips.thumbnail()

        def load_images_threadsafe(imagefiles):
            """Load, resize, and pad images with black bars to TARGET_SIZE using PyVips (multi-threaded)."""
            images = [None] * len(imagefiles)
            objs = [None] * len(imagefiles)

            with ThreadPoolExecutor(
                max_workers=max(1, self.threads - 1), thread_name_prefix="mobilenet_thumbs"
            ) as executor:
                futures = {executor.submit(self.gui.imagegrid.thumbs.gen_thumb, obj, size=TARGET_SIZE, cache_dir=None, user="mobilenet", mode="letterbox"): i
                        for i, obj in enumerate(imagefiles)}

                for f in as_completed(futures):
                    i = futures[f]
                    result = f.result()
                    if isinstance(result, tuple):
                        img, obj = result
                        if img is not None and obj is not None:
                            images[i] = img
                            objs[i] = obj

            # Filter out failed loads while preserving order
            valid = [(img, obj) for img, obj in zip(images, objs) if img is not None and obj is not None]
            if not valid:
                return np.empty((0, TARGET_SIZE, TARGET_SIZE, 3), dtype=np.uint8), []

            images, objs = zip(*valid)
            return np.stack(images), list(objs)

        def letterbox(img, size):
            w, h = img.size
            new_im = Image.new("RGB", (size, size), (114, 114, 114))
            left = (size - w) // 2
            top = (size - h) // 2
            new_im.paste(img, (left, top))
            return new_im
        def threaded_letterboxing(images):
            thumbs = [None] * len(images)

            with ThreadPoolExecutor(
                max_workers=max(1, self.threads - 1), thread_name_prefix="mobilenet_thumbs"
            ) as executor:
                futures = {executor.submit(letterbox, img, size=TARGET_SIZE): i for i, img in enumerate(images)}
                for f in as_completed(futures):
                    i = futures[f]
                    thumbs[i] = f.result()

            return thumbs

        def get_mobilenet_embeddings(images):
            """Compute MobileNet feature embeddings in batches."""
            import torch
            import torchvision.transforms as T
            import torchvision.models as models
            from torchvision.models import MobileNet_V2_Weights
            device = "cuda" if torch.cuda.is_available() else "cpu"
            #model = models.mobilenet_v2(weights=MobileNet_V2_Weights.DEFAULT).to(device)
            model = models.mobilenet_v2(weights=MobileNet_V2_Weights.IMAGENET1K_V1).to(device)
            model.eval()

            preprocess = T.Compose([
                T.Resize(224),
                T.CenterCrop(224),
                T.ToTensor(),
                T.Normalize(mean=[0.485, 0.456, 0.406],
                            std=[0.229, 0.224, 0.225]),
            ])

            all_emb = []
            with torch.no_grad():
                for i in range(0, len(images), BATCH_SIZE):
                    print("Embed:", i+BATCH_SIZE)
                    batch = images[i:i+BATCH_SIZE]
                    batch_tensor = torch.stack([preprocess(Image.fromarray(img)) for img in batch]).to(device)
                    feats = model.features(batch_tensor)
                    pooled = torch.nn.functional.adaptive_avg_pool2d(feats, (1, 1)).view(len(batch), -1)
                    all_emb.append(pooled.cpu().numpy())

            embeddings = np.concatenate(all_emb, axis=0)
            embeddings /= np.linalg.norm(embeddings, axis=1, keepdims=True)
            return embeddings

        def get_dominant_center_color(img, crop_ratio=0.6, similarity_threshold=32):
            try:
                img_f = img.astype(np.float32)
                h, w, _ = img_f.shape

                # --- Center crop ---
                ch, cw = int(h * crop_ratio), int(w * crop_ratio)
                top, left = (h - ch) // 2, (w - cw) // 2
                center_crop = img_f[top:top+ch, left:left+cw].reshape(-1, 3)

                # --- Background crop ---
                mask = np.ones((h, w), dtype=bool)
                mask[top:top+ch, left:left+cw] = False
                background_crop = img_f[mask].reshape(-1, 3)

                if len(background_crop) == 0:
                    return np.median(center_crop, axis=0)

                # --- Compute distances from background pixels ---
                # Using simple RGB Euclidean distance
                bg_median = np.median(background_crop, axis=0)
                dists = np.linalg.norm(center_crop - bg_median[None, :], axis=1)

                # Keep pixels that are sufficiently different from background
                fg_pixels = center_crop[dists > similarity_threshold]

                if len(fg_pixels) == 0:
                    # fallback: use center crop median
                    fg_pixels = center_crop

                dominant_color = np.median(fg_pixels, axis=0)
                return np.clip(dominant_color, 0, 255)

            except Exception:
                return np.median(img_f.reshape(-1, 3), axis=0)

        def get_median_center_color(img, crop_ratio=0.5):
            """Compute median center color in RGB for each image."""
            try:
                h, w, _ = img.shape
                ch, cw = int(h * crop_ratio), int(w * crop_ratio)
                top = (h - ch) // 2
                left = (w - cw) // 2
                crop = img[top:top+ch, left:left+cw]
                return np.median(crop.reshape(-1, 3), axis=0)
            except Exception:
                return np.zeros(3)

        def get_order_tsp(combined, k=20):
            """Use k-nearest neighbor TSP-like heuristic for smoother ordering."""
            import faiss
            index = faiss.IndexFlatL2(combined.shape[1])
            index.add(combined.astype(np.float32))
            D, I = index.search(combined.astype(np.float32), k)

            visited = np.zeros(len(combined), dtype=bool)
            order = [0]
            visited[0] = True

            for _ in range(1, len(combined)):
                last = order[-1]
                found = False

                # Try nearest neighbors first
                for neighbor in I[last]:
                    if not visited[neighbor]:
                        order.append(neighbor)
                        visited[neighbor] = True
                        found = True
                        break

                # Fallback: find globally nearest unvisited
                if not found:
                    unvisited = np.where(~visited)[0]
                    if len(unvisited) == 0:
                        break
                    # use FAISS to find closest among remaining
                    D2, I2 = index.search(combined[last:last+1].astype(np.float32), len(combined))
                    for neighbor in I2[0]:
                        if not visited[neighbor]:
                            order.append(neighbor)
                            visited[neighbor] = True
                            break
            return order

        if optimization:
            images, objs_to_encode = optimization
            images = threaded_letterboxing(images)
            if not images: images, objs_to_encode = np.empty((0, TARGET_SIZE, TARGET_SIZE, 3), dtype=np.uint8), []
            else:
                images = np.stack(images)
        else:
            test = sorted(imagefiles, key=lambda x: x.name)
            images, objs_to_encode = load_images_threadsafe(test)

        alpha = 0.7 if PRESET == 1 else 0.4

        with ThreadPoolExecutor(max_workers=max(1, self.threads - 1), thread_name_prefix="mobilenet-colors") as executor:
            func = get_dominant_center_color if PRESET == 1 else get_median_center_color
            futures = {executor.submit(func, img): i for i, img in enumerate(images)}
            dominant_colors = [None] * len(images)

            for f in as_completed(futures):
                i = futures[f]
                dominant_colors[i] = f.result()

            color_emb_new = np.array(dominant_colors, dtype=np.float32)

            for obj, col in zip(objs_to_encode, color_emb_new):
                obj.color_embed = np.asarray(col, dtype=np.float32)

            if len(objs_to_encode) > 0:
                embeddings_new = get_mobilenet_embeddings(images)
                for obj, emb in zip(objs_to_encode, embeddings_new):
                    obj.embed = np.asarray(emb, dtype=np.float32)


        if optimization:
            print("Embeds preloaded for list in:", perf_counter()-start)
            return
        objs_with_both = [
            obj for obj in test
            if getattr(obj, "embed", None) is not None and getattr(obj, "color_embed", None) is not None
        ]
        if len(objs_with_both) == 0:
            print("No objects with both embed and color_embed — aborting.")
            return

        # 5) Stack arrays in the same order
        all_emb = np.vstack([np.asarray(obj.embed, dtype=np.float32).reshape(1, -1) for obj in objs_with_both])
        color_emb = np.vstack([np.asarray(obj.color_embed, dtype=np.float32).reshape(1, -1) for obj in objs_with_both])

        # 6) normalize color embeddings safely
        norms = np.linalg.norm(color_emb, axis=1, keepdims=True)
        norms[norms == 0] = 1e-8
        color_emb /= norms

        combined = np.concatenate([alpha * all_emb, (1 - alpha) * color_emb], axis=1)
        order = get_order_tsp(combined)

        ordered_objs = [objs_with_both[idx] for idx in reversed(order)]

        remaining = [o for o in imagefiles if o not in objs_with_both]
        imagefiles[:] = ordered_objs + remaining
        if reverse:
            imagefiles.reverse()

        print("Reorder nearest time:", perf_counter()-start)

    def update_info(self, old=None): # debug so will stay here
        import psutil
        def get_memory_usage():
            process = psutil.Process()
            memory_info = process.memory_info()
            return (memory_info.rss)
        if self.gui.do_debug.get(): self.gui.ram_label["text"] = f"RAM: {get_memory_usage() / (1024 ** 2):.2f} MB"

        "Anim: displayedlist with frames/displayedlist with framecount/(queue)"
        if self.gui.imagegrid:
            temp = [x for x in self.gui.imagegrid.image_items if x.file.frames]
            self.gui.animation_stats_var.set(f"Objs In animate/With references: {len(self.gui.imagegrid.animate.running)}/{len(temp)}")

            "Frames: frames + frames_dest / max"
            temp = [x.file.frames for x in self.gui.imagegrid.image_items if x.file.frames]
            c = 0
            for x in temp:
                c += len(x)
            self.gui.resource_limiter_var.set(f"{c}/{self.max_concurrent_frames}")

            self.concurrent_frames = c
            with self.gui.imagegrid.thumbs._cf_cond:
                self.gui.imagegrid.thumbs._cf_cond.notify_all()

        self.gui.after(333, self.update_info)

if __name__ == '__main__':
    ctypes.windll.shcore.SetProcessDpiAwareness(1)
    mp.freeze_support()
    try: mp.set_start_method('spawn', force=True)
    except RuntimeError: pass
    script_dir = os.path.dirname(os.path.abspath(__file__))
    prefs_path = os.path.join(script_dir, "_prefs.json")
    themes_path = os.path.join(script_dir, "_themes.json")

    def loadprefs():
        "Loads prefs.json. Needs self.gui to be created. This edits self.gui attributes."
        if not os.path.isfile(prefs_path):
            with open(prefs_path, "w") as prefsfile:
                pass
        try:
            with open(prefs_path, "r") as prefsfile:
                jdata = prefsfile.read()
                if jdata == "":
                    return {}
                jprefs = json.loads(jdata)
                return jprefs
        except Exception as e:
            print(f"Error loading prefs.json: {e}")
            return {}

    def load_themes():
        try:
            with open(themes_path, "r") as themesfile:
                jdata = themesfile.read()
                jthemes = json.loads(jdata)
                return jthemes["themes"]
        except Exception as e:
            print("Error loading themes:", e)
            return {}

    jthemes = load_themes()
    prefs = loadprefs()

    gui = GUIManager(prefs, jthemes)
    mainclass = SortImages(gui)
    gui.fileManager = mainclass

    parser = argparse.ArgumentParser(description="Image sorting and processing script.")
    parser.add_argument('-quick', action='store_true', help='Enable quick sorting mode')
    parser.add_argument('folder_path', type=str, nargs='?')
    args = parser.parse_args()

    if args.quick: # start at the current directory.
        if args.folder_path: path = args.folder_path
        else: path = os.getcwd()
        gui.source_entry_field.delete(0, tk.END)
        gui.destination_entry_field.delete(0, tk.END)
        gui.source_entry_field.insert(0, path)
        gui.destination_entry_field.insert(0, path)
        gui.after_idle(gui.fileManager.validate)
    gui.mainloop()

